services:
  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: diary_database
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 976431
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    build: .
    command: >
      sh -c "sleep 10 && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DB_NAME=diary_database
      - DB_USER=postgres
      - DB_PASSWORD=976431
      - DB_HOST=db
      - DB_PORT=5432
      - SECRET_KEY=your-docker-secret-key-change-in-production
      - DEBUG=True
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data: