[tool.poetry]
name = "diploma-thesis-web-application"
version = "0.1.0"
description = ""
authors = ["Your Name <your@email.com>"]
readme = "README.md"
packages = []
include = []

[tool.poetry.dependencies]
python = "^3.13"
django = "^5.2.7"
psycopg2-binary = "^2.9.10"
django-environ = "^0.12.0"
